export const countries = [
  { name: "Afghanistan", position: { lat: 33, lon: 65 }, code: "af", lcode: "ps" },
  { name: "Albania", position: { lat: 41, lon: 20 }, code: "al", lcode: "sq" },
  { name: "Algeria", position: { lat: 28, lon: 3 }, code: "dz", lcode: "ar" },
  { name: "Andorra", position: { lat: 42.5, lon: 1.6 }, code: "ad", lcode: "ca" },
  { name: "Angola", position: { lat: -12.5, lon: 18.5 }, code: "ao", lcode: "pt" },
  { name: "Antigua and Barbuda", position: { lat: 17.05, lon: -61.8 }, code: "ag", lcode: "en" },
  { name: "Argentina", position: { lat: -34, lon: -64 }, code: "ar", lcode: "es" },
  { name: "Armenia", position: { lat: 40, lon: 45 }, code: "am", lcode: "hy" },
  { name: "Australia", position: { lat: -27, lon: 133 }, code: "au", lcode: "en" },
  { name: "Austria", position: { lat: 47.3333, lon: 13.3333 }, code: "at", lcode: "de" },
  { name: "Azerbaijan", position: { lat: 40.5, lon: 47.5 }, code: "az", lcode: "az" },
  { name: "Bahamas", position: { lat: 24.25, lon: -76 }, code: "bs", lcode: "en" },
  { name: "Bahrain", position: { lat: 26, lon: 50.55 }, code: "bh", lcode: "ar" },
  { name: "Bangladesh", position: { lat: 24, lon: 90 }, code: "bd", lcode: "bn" },
  { name: "Barbados", position: { lat: 13.1667, lon: -59.5333 }, code: "bb", lcode: "en" },
  { name: "Belarus", position: { lat: 53, lon: 28 }, code: "by", lcode: "be" },
  { name: "Belgium", position: { lat: 50.8333, lon: 4 }, code: "be", lcode: "nl" },
  { name: "Belize", position: { lat: 17.25, lon: -88.75 }, code: "bz", lcode: "en" },
  { name: "Benin", position: { lat: 9.5, lon: 2.25 }, code: "bj", lcode: "fr" },
  { name: "Bhutan", position: { lat: 27.5, lon: 90.5 }, code: "bt", lcode: "dz" },
  { name: "Bolivia", position: { lat: -17, lon: -65 }, code: "bo", lcode: "es" },
  { name: "Bosnia And Herzegovina", position: { lat: 44, lon: 18 }, code: "ba", lcode: "bs" },
  { name: "Botswana", position: { lat: -22, lon: 24 }, code: "bw", lcode: "en" },
  { name: "Brazil", position: { lat: -10, lon: -55 }, code: "br", lcode: "pt" },
  { name: "Brunei", position: { lat: 4.5, lon: 114.6667 }, code: "bn", lcode: "ms" },
  { name: "Bulgaria", position: { lat: 43, lon: 25 }, code: "bg", lcode: "bg" },
  { name: "Burkina Faso", position: { lat: 13, lon: -2 }, code: "bf", lcode: "fr" },
  { name: "Burundi", position: { lat: -3.5, lon: 30 }, code: "bi", lcode: "rn" },
  { name: "Côte d'Ivoire", position: { lat: 8, lon: -5 }, code: "ci", lcode: "fr" },
  { name: "Cape Verde", position: { lat: 16, lon: -24 }, code: "cv", lcode: "pt" },
  { name: "Cambodia", position: { lat: 13, lon: 105 }, code: "kh", lcode: "km" },
  { name: "Cameroon", position: { lat: 6, lon: 12 }, code: "cm", lcode: "en" },
  { name: "Canada", position: { lat: 60, lon: -95 }, code: "ca", lcode: "en" },
  { name: "Central African Republic", position: { lat: 7, lon: 21 }, code: "cf", lcode: "fr" },
  { name: "Chad", position: { lat: 15, lon: 19 }, code: "td", lcode: "fr" },
  { name: "Chile", position: { lat: -30, lon: -71 }, code: "cl", lcode: "es" },
  { name: "China", position: { lat: 35, lon: 105 }, code: "cn", lcode: "zh" },
  { name: "Colombia", position: { lat: 4, lon: -72 }, code: "co", lcode: "es" },
  { name: "Comoros", position: { lat: -12.1667, lon: 44.25 }, code: "km", lcode: "ar" },
  { name: "Congo", position: { lat: -1, lon: 15 }, code: "cg", lcode: "fr" },
  { name: "Costa Rica", position: { lat: 10, lon: -84 }, code: "cr", lcode: "es" },
  { name: "Croatia", position: { lat: 45.1667, lon: 15.5 }, code: "hr", lcode: "hr" },
  { name: "Cuba", position: { lat: 21.5, lon: -80 }, code: "cu", lcode: "es" },
  { name: "Cyprus", position: { lat: 35, lon: 33 }, code: "cy", lcode: "el" },
  { name: "Czechia", position: { lat: 49.75, lon: 15.5 }, code: "cz", lcode: "cs" },
  { name: "Democratic Republic of the Congo", position: { lat: 0, lon: 25 }, code: "cd", lcode: "fr" },
  { name: "Denmark", position: { lat: 56, lon: 10 }, code: "dk", lcode: "da" },
  { name: "Djibouti", position: { lat: 11.5, lon: 43 }, code: "dj", lcode: "fr" },
  { name: "Dominica", position: { lat: 15.4167, lon: -61.3333 }, code: "dm", lcode: "en" },
  { name: "Dominican Republic", position: { lat: 19, lon: -70.6667 }, code: "do", lcode: "es" },
  { name: "Ecuador", position: { lat: -2, lon: -77.5 }, code: "ec", lcode: "es" },
  { name: "Egypt", position: { lat: 27, lon: 30 }, code: "eg", lcode: "ar" },
  { name: "El Salvador", position: { lat: 13.8333, lon: -88.9167 }, code: "sv", lcode: "es" },
  { name: "Equatorial Guinea", position: { lat: 2, lon: 10 }, code: "gq", lcode: "es" },
  { name: "Eritrea", position: { lat: 15, lon: 39 }, code: "er", lcode: "ti" },
  { name: "Estonia", position: { lat: 59, lon: 26 }, code: "ee", lcode: "et" },
  { name: "Swaziland", position: { lat: -26.5, lon: 31.5 }, code: "sz", lcode: "en" },
  { name: "Ethiopia", position: { lat: 8, lon: 38 }, code: "et", lcode: "am" },
  { name: "Fiji", position: { lat: -18, lon: 178 }, code: "fj", lcode: "en" },
  { name: "Finland", position: { lat: 64, lon: 26 }, code: "fi", lcode: "fi" },
  { name: "France", position: { lat: 46, lon: 2 }, code: "fr", lcode: "fr" },
  { name: "Gabon", position: { lat: -1, lon: 11.75 }, code: "ga", lcode: "fr" },
  { name: "Gambia", position: { lat: 13.4667, lon: -16.5667 }, code: "gm", lcode: "en" },
  { name: "Georgia", position: { lat: 42, lon: 43.5 }, code: "ge", lcode: "ka" },
  { name: "Germany", position: { lat: 51, lon: 9 }, code: "de", lcode: "de" },
  { name: "Ghana", position: { lat: 8, lon: -1 }, code: "gh", lcode: "en" },
  { name: "Greece", position: { lat: 39, lon: 22 }, code: "gr", lcode: "el" },
  { name: "Grenada", position: { lat: 12.1167, lon: -61.6667 }, code: "gd", lcode: "en" },
  { name: "Guatemala", position: { lat: 15.5, lon: -90.25 }, code: "gt", lcode: "es" },
  { name: "Guinea", position: { lat: 11, lon: -10 }, code: "gn", lcode: "fr" },
  { name: "Guinea-Bissau", position: { lat: 12, lon: -15 }, code: "gw", lcode: "pt" },
  { name: "Guyana", position: { lat: 5, lon: -59 }, code: "gy", lcode: "en" },
  { name: "Haiti", position: { lat: 19, lon: -72.4167 }, code: "ht", lcode: "ht" },
  { name: "Honduras", position: { lat: 13.5, lon: -83 }, code: "hn", lcode: "es" },
  { name: "Hungary", position: { lat: 47, lon: 20 }, code: "hu", lcode: "hu" },
  { name: "Iceland", position: { lat: 65, lon: -18 }, code: "is", lcode: "is" },
  { name: "India", position: { lat: 20, lon: 77 }, code: "in", lcode: "hi" },
  { name: "Indonesia", position: { lat: -5, lon: 120 }, code: "id", lcode: "id" },
  { name: "Iran", position: { lat: 32, lon: 53 }, code: "ir", lcode: "fa" },
  { name: "Iraq", position: { lat: 33, lon: 44 }, code: "iq", lcode: "ar" },
  { name: "Ireland", position: { lat: 53, lon: -8 }, code: "ie", lcode: "en" },
  { name: "Israel", position: { lat: 31.5, lon: 34.75 }, code: "il", lcode: "he" },
  { name: "Italy", position: { lat: 42.8333, lon: 12.8333 }, code: "it", lcode: "it" },
  { name: "Jamaica", position: { lat: 18.25, lon: -77.5 }, code: "jm", lcode: "en" },
  { name: "Japan", position: { lat: 36, lon: 138 }, code: "jp", lcode: "ja" },
  { name: "Jordan", position: { lat: 31, lon: 36 }, code: "jo", lcode: "ar" },
  { name: "Kazakhstan", position: { lat: 48, lon: 68 }, code: "kz", lcode: "kk" },
  { name: "Kenya", position: { lat: -1.5, lon: 38 }, code: "ke", lcode: "en" },
  { name: "Kiribati", position: { lat: 1.4167, lon: 173 }, code: "ki", lcode: "en" },
  { name: "North Korea", position: { lat: 40, lon: 127 }, code: "kp", lcode: "ko" },
  { name: "Korea (South)", position: { lat: 35, lon: 127 }, code: "kr", lcode: "ko" },
  { name: "Kuwait", position: { lat: 29.5, lon: 45.75 }, code: "kw", lcode: "ar" },
  { name: "Kyrgyzstan", position: { lat: 41, lon: 75 }, code: "kg", lcode: "ky" },
  { name: "Laos", position: { lat: 18, lon: 105 }, code: "la", lcode: "lo" },
  { name: "Latvia", position: { lat: 57, lon: 25 }, code: "lv", lcode: "lv" },
  { name: "Lebanon", position: { lat: 33.8333, lon: 35.8333 }, code: "lb", lcode: "ar" },
  { name: "Lesotho", position: { lat: -29.5, lon: 28.5 }, code: "ls", lcode: "en" },
  { name: "Liberia", position: { lat: 6.5, lon: -9.5 }, code: "lr", lcode: "en" },
  { name: "Libya", position: { lat: 25, lon: 17 }, code: "ly", lcode: "ar" },
  { name: "Liechtenstein", position: { lat: 47.1667, lon: 9.5333 }, code: "li", lcode: "de" },
  { name: "Lithuania", position: { lat: 55, lon: 24 }, code: "lt", lcode: "lt" },
  { name: "Luxembourg", position: { lat: 49.75, lon: 6.1667 }, code: "lu", lcode: "lb" },
  { name: "Madagascar", position: { lat: -20, lon: 47 }, code: "mg", lcode: "mg" },
  { name: "Malawi", position: { lat: -13.5, lon: 34 }, code: "mw", lcode: "ny" },
  { name: "Malaysia", position: { lat: 2.5, lon: 112.5 }, code: "my", lcode: "ms" },
  { name: "Maldives", position: { lat: 3.25, lon: 73 }, code: "mv", lcode: "dv" },
  { name: "Mali", position: { lat: 17, lon: -4 }, code: "ml", lcode: "fr" },
  { name: "Malta", position: { lat: 35.8333, lon: 14.5833 }, code: "mt", lcode: "mt" },
  { name: "Marshall Islands", position: { lat: 9, lon: 168 }, code: "mh", lcode: "en" },
  { name: "Mauritania", position: { lat: 20, lon: -12 }, code: "mr", lcode: "ar" },
  { name: "Mauritius", position: { lat: -20.2833, lon: 57.55 }, code: "mu", lcode: "en" },
  { name: "Mexico", position: { lat: 23, lon: -102 }, code: "mx", lcode: "es" },
  { name: "Micronesia", position: { lat: 7, lon: 158 }, code: "fm", lcode: "en" },
  { name: "Moldova", position: { lat: 47, lon: 29 }, code: "md", lcode: "ro" },
  { name: "Monaco", position: { lat: 43.7333, lon: 7.4167 }, code: "mc", lcode: "fr" },
  { name: "Mongolia", position: { lat: 46, lon: 105 }, code: "mn", lcode: "mn" },
  { name: "Montenegro", position: { lat: 42.5, lon: 19.3 }, code: "me", lcode: "sr" },
  { name: "Morocco", position: { lat: 32, lon: -5 }, code: "ma", lcode: "ar" },
  { name: "Mozambique", position: { lat: -18.25, lon: 35 }, code: "mz", lcode: "pt" },
  { name: "Myanmar", position: { lat: 21.9162, lon: 95.955 }, code: "mm", lcode: "my" },
  { name: "Namibia", position: { lat: -22, lon: 17 }, code: "na", lcode: "en" },
  { name: "Nauru", position: { lat: -0.5333, lon: 166.9167 }, code: "nr", lcode: "en" },
  { name: "Nepal", position: { lat: 28, lon: 84 }, code: "np", lcode: "ne" },
  { name: "Netherlands", position: { lat: 52.5, lon: 5.75 }, code: "nl", lcode: "nl" },
  { name: "New Zealand", position: { lat: -40.5, lon: 172.6667 }, code: "nz", lcode: "en" },
  { name: "Nicaragua", position: { lat: 13, lon: -85 }, code: "ni", lcode: "es" },
  { name: "Niger", position: { lat: 16, lon: 8 }, code: "ne", lcode: "fr" },
  { name: "Nigeria", position: { lat: 10, lon: 8 }, code: "ng", lcode: "en" },
  { name: "Macedonia", position: { lat: 41.8333, lon: 22 }, code: "mk", lcode: "mk" },
  { name: "Norway", position: { lat: 62, lon: 10 }, code: "no", lcode: "no" },
  { name: "Oman", position: { lat: 21, lon: 57 }, code: "om", lcode: "ar" },
  { name: "Pakistan", position: { lat: 30, lon: 70 }, code: "pk", lcode: "ur" },
  { name: "Palau", position: { lat: 7.5, lon: 134.5 }, code: "pw", lcode: "en" },
  { name: "Panama", position: { lat: 8.5, lon: -80 }, code: "pa", lcode: "es" },
  { name: "Papua New Guinea", position: { lat: -6, lon: 147 }, code: "pg", lcode: "en" },
  { name: "Paraguay", position: { lat: -23, lon: -58 }, code: "py", lcode: "es" },
  { name: "Peru", position: { lat: -10, lon: -76 }, code: "pe", lcode: "es" },
  { name: "Philippines", position: { lat: 13, lon: 122 }, code: "ph", lcode: "tl" },
  { name: "Poland", position: { lat: 52, lon: 19 }, code: "pl", lcode: "pl" },
  { name: "Portugal", position: { lat: 39.5, lon: -8 }, code: "pt", lcode: "pt" },
  { name: "Qatar", position: { lat: 25.5, lon: 51.25 }, code: "qa", lcode: "ar" },
  { name: "Romania", position: { lat: 46, lon: 25 }, code: "ro", lcode: "ro" },
  { name: "Russia", position: { lat: 60, lon: 100 }, code: "ru", lcode: "ru" },
  { name: "Rwanda", position: { lat: -2, lon: 30 }, code: "rw", lcode: "rw" },
  { name: "Saint Kitts and Nevis", position: { lat: 17.3333, lon: -62.75 }, code: "kn", lcode: "en" },
  { name: "Saint Lucia", position: { lat: 13.8833, lon: -60.9667 }, code: "lc", lcode: "en" },
  { name: "Saint Vincent and the Grenadines", position: { lat: 13.25, lon: -61.2 }, code: "vc", lcode: "en" },
  { name: "Samoa", position: { lat: -13.5833, lon: -172.3333 }, code: "ws", lcode: "en" },
  { name: "San Marino", position: { lat: 43.9333, lon: 12.45 }, code: "sm", lcode: "it" },
  { name: "Sao Tome and Principe", position: { lat: 1, lon: 7 }, code: "st", lcode: "pt" },
  { name: "Saudi Arabia", position: { lat: 25, lon: 45 }, code: "sa", lcode: "ar" },
  { name: "Senegal", position: { lat: 14, lon: -14 }, code: "sn", lcode: "fr" },
  { name: "Serbia", position: { lat: 44, lon: 21 }, code: "rs", lcode: "sr" },
  { name: "Seychelles", position: { lat: -4.5833, lon: 55.6667 }, code: "sc", lcode: "en" },
  { name: "Sierra Leone", position: { lat: 8.5, lon: -11.5 }, code: "sl", lcode: "en" },
  { name: "Singapore", position: { lat: 1.3667, lon: 103.8 }, code: "sg", lcode: "en" },
  { name: "Slovakia", position: { lat: 48.6667, lon: 19.5 }, code: "sk", lcode: "sk" },
  { name: "Slovenia", position: { lat: 46, lon: 15 }, code: "si", lcode: "sl" },
  { name: "Solomon Islands", position: { lat: -10, lon: 160 }, code: "sb", lcode: "en" },
  { name: "Somalia", position: { lat: 5, lon: 47 }, code: "so", lcode: "so" },
  { name: "South Africa", position: { lat: -30, lon: 24 }, code: "za", lcode: "en" },
  { name: "South Sudan", position: { lat: 8, lon: 30 }, code: "ss", lcode: "en" },
  { name: "Spain", position: { lat: 40, lon: -4 }, code: "es", lcode: "es" },
  { name: "Sri Lanka", position: { lat: 7, lon: 81 }, code: "lk", lcode: "si" },
  { name: "Sudan", position: { lat: 15, lon: 30 }, code: "sd", lcode: "ar" },
  { name: "Suriname", position: { lat: 4, lon: -56 }, code: "sr", lcode: "nl" },
  { name: "Sweden", position: { lat: 62, lon: 15 }, code: "se", lcode: "sv" },
  { name: "Switzerland", position: { lat: 47, lon: 8 }, code: "ch", lcode: "de" },
  { name: "Syria", position: { lat: 33.5, lon: 36.5 }, code: "sy", lcode: "ar" },
  { name: "Taiwan", position: { lat: 23.5, lon: 121 }, code: "tw", lcode: "zh" },
  { name: "Tajikistan", position: { lat: 39, lon: 71 }, code: "tj", lcode: "tg" },
  { name: "Tanzania", position: { lat: -6, lon: 35 }, code: "tz", lcode: "sw" },
  { name: "Thailand", position: { lat: 15, lon: 100 }, code: "th", lcode: "th" },
  { name: "Timor-Leste", position: { lat: -8.8333, lon: 125.8333 }, code: "tl", lcode: "tet" },
  { name: "Togo", position: { lat: 8, lon: 1 }, code: "tg", lcode: "fr" },
  { name: "Tonga", position: { lat: -20, lon: -175 }, code: "to", lcode: "en" },
  { name: "Trinidad and Tobago", position: { lat: 10.5, lon: -61.5 }, code: "tt", lcode: "en" },
  { name: "Tunisia", position: { lat: 34, lon: 9 }, code: "tn", lcode: "ar" },
  { name: "Turkey", position: { lat: 39, lon: 35 }, code: "tr", lcode: "tr" },
  { name: "Turkmenistan", position: { lat: 40, lon: 60 }, code: "tm", lcode: "tk" },
  { name: "Tuvalu", position: { lat: -7, lon: 179 }, code: "tv", lcode: "en" },
  { name: "Uganda", position: { lat: 1, lon: 32 }, code: "ug", lcode: "en" },
  { name: "Ukraine", position: { lat: 49, lon: 32 }, code: "ua", lcode: "uk" },
  { name: "United Arab Emirates", position: { lat: 24, lon: 54 }, code: "ae", lcode: "ar" },
  { name: "United Kingdom", position: { lat: 54, lon: -2 }, code: "gb", lcode: "en" },
  { name: "United States", position: { lat: 37.5, lon: -96.5 }, code: "us", lcode: "en" },
  { name: "Uruguay", position: { lat: -33, lon: -56 }, code: "uy", lcode: "es" },
  { name: "Uzbekistan", position: { lat: 41, lon: 64 }, code: "uz", lcode: "uz" },
  { name: "Vanuatu", position: { lat: -15, lon: 167 }, code: "vu", lcode: "en" },
  { name: "Vatican City", position: { lat: 41.9, lon: 12.45 }, code: "va", lcode: "it" },
  { name: "Venezuela", position: { lat: 8, lon: -66 }, code: "ve", lcode: "es" },
  { name: "Vietnam", position: { lat: 14, lon: 108 }, code: "vn", lcode: "vi" },
  { name: "Yemen", position: { lat: 15, lon: 48 }, code: "ye", lcode: "ar" },
  { name: "Zambia", position: { lat: -15, lon: 30 }, code: "zm", lcode: "en" },
  { name: "Zimbabwe", position: { lat: -20, lon: 30 }, code: "zw", lcode: "en" }
];
